#!/bin/bash

if [ -z "$BRANCHES_TO_SKIP" ]; then
  BRANCHES_TO_SKIP=(main develop release hotfix)
fi


NUMBER_REGEX="^[0-9]+$"
TICKET_REGEX="^\[\w+\s?: #[0-9]+]"

NAME=$(git branch | grep '*' | sed 's/* //')

BRANCH_NAME=$(git symbolic-ref --short HEAD)
ISSUE_NUMBER="${BRANCH_NAME##*/}"

COMMIT_MESSAGE="$(cat $1)"
MESSAGE=`echo $COMMIT_MESSAGE | cut -d ':' -f2`
DESCRIPTION=$(git config branch."$NAME".description)
FREFIX=`echo $COMMIT_MESSAGE | cut -d ':' -f1`

if [[ $COMMIT_MESSAGE =~ $TICKET_REGEX ]];then
  exit 0;
fi

if [[ "$COMMIT_MESSAGE" =~ ":" ]];then
    ISSUE="$FREFIX: #$ISSUE_NUMBER"
else
    ISSUE="#$ISSUE_NUMBER"
fi

if [[ $ISSUE_NUMBER =~ $NUMBER_REGEX ]] && ! [[ $BRANCH_EXCLUDED -eq 1 ]]
then
  echo "[$ISSUE] $MESSAGE" > $1
  if [ -n "$DESCRIPTION" ]
  then
    echo "" >> "$1"
    echo $DESCRIPTION >> "$1"
  fi
fi
